### ISSUE TITLE
프로젝트 생성

### ISSUE THREAD

**Issue by younghyun-na** [weekly-academy/fridge-friend#2]
## Description
프로젝트 생성하기  

#### 구성 버전 정보
+ Spring Boot 2.7.8
+ Java 11
+ Gradle

## Todo
- [x] Gitflow 전략 공부하기
- [x] 프로젝트 생성하기

**Comment by heli-os** [comment]
지나가다가 봤는데, 이거 오타인줄 알았더니.. 아티팩트가 바뀐거군요?!

https://github.com/weekly-academy/fridge-friend/commit/43c5559e77dcbb6345d2ab0f76b3f13d12b764b9#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R25

**Comment by heli-os** [comment]
이슈나 PR 어싸인은 @younghyun-na 님으로 해주세요~
